### ISSUE TITLE
LinkML test error

### ISSUE THREAD

**Issue by sbliven** [osc-em/OSCEM_Schemas#10]
Running `make all` on the linkml_yaml branch fails with the following error:

```

Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/oscem-schemas-HjusQlgA-py3.10/bin/linkml-run-examples", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/.cache/pypoetry/virtualenvs/oscem-schemas-HjusQlgA-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/oscem-schemas-HjusQlgA-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/runner/.cache/pypoetry/virtualenvs/oscem-schemas-HjusQlgA-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.cache/pypoetry/virtualenvs/oscem-schemas-HjusQlgA-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/oscem-schemas-HjusQlgA-py3.10/lib/python3.10/site-packages/linkml/workspaces/example_runner.py", line 313, in cli
    runner.process_examples()
  File "/home/runner/.cache/pypoetry/virtualenvs/oscem-schemas-HjusQlgA-py3.10/lib/python3.10/site-packages/linkml/workspaces/example_runner.py", line 138, in process_examples
    self.process_examples_from_list(input_examples, fmt, False)
  File "/home/runner/.cache/pypoetry/virtualenvs/oscem-schemas-HjusQlgA-py3.10/lib/python3.10/site-packages/linkml/workspaces/example_runner.py", line 193, in process_examples_from_list
    raise ValueError(f"Example {input_example} failed validation:\n{e}")
ValueError: Example src/data/examples/EMDataset-001.yaml failed validation:
unhashable type: 'Institution'
```

**Comment by sbliven** [comment]
This is run by the CI, so PRs like #9 fail.

I think it might be python-specific. Running `linkml-lint` directly doesn't report errors. The cookie cutter uses the python bindings for testing, but we mostly care about the schema itself as well as the jsonschema derived files

**Comment by sbliven** [comment]
Fixed now
